### ISSUE TITLE
release 0.1-1 checklist

### ISSUE THREAD

**Issue by rfairley** [rfairley/console-login-helper-messages#11]
- [x] documentation in README.md (#8, #9, #10)
- [x] build has been done in copr and tested on:
    - [x] Fedora Cloud Base {28, 29, 30} 
    - [x] Fedora Atomic Host {28, 29, 30} 
    - [x] Fedora CoreOS
- [x] license is added, and attributions given
- [x] upload `.tar.gz` of source code on GitHub

**Comment by rfairley** [comment]
Done by release [v0.1](https://github.com/rfairley/console-login-helper-messages/releases/tag/v0.1).
